<template>
    <div id="app" style="text-align: center;width: 90%; margin: auto;margin-top: 2%">
        <div id="main" style="width: 100%;height:600px;margin:0 auto"></div>
    </div>
</template>
<script>
  require('echarts-wordcloud')
  export default {
    name: 'javaWordCloud',
    data () {
      return {
        datas:[{'name':"掌握常用", "value":23},
          {'name':"精通主流", "value":11},
          {'name':"数据库开发", "value":15},
          {'name':"完成系统", "value":15},
          {'name':"常用中间", "value":13},
          {'name':"常用框架", "value":19},
          {'name':"表达能力", "value":31},
          {'name':"参与公司", "value":21},
          {'name':"熟悉消息", "value":12},
          {'name':"统招本科", "value":35},
          {'name':"高并发", "value":86},
          {'name':"相关经验", "value":31},
          {'name':"代码实现", "value":15},
          {'name':"熟悉系统", "value":34},
          {'name':"任职资格", "value":56},
          {'name':"沟通能力", "value":92},
          {'name':"具备一定", "value":18},
          {'name':"善于沟通", "value":21},
          {'name':"研发经验", "value":29},
          {'name':"系统开发", "value":58},
          {'name':"熟练使用", "value":118},
          {'name':"深入理解", "value":36},
          {'name':"测试工作", "value":12},
          {'name':"项目中", "value":13},
          {'name':"开发中", "value":12},
          {'name':"大专学历", "value":18},
          {'name':"精通开发", "value":16},
          {'name':"设计模式", "value":104},
          {'name':"协作精神", "value":16},
          {'name':"服务开发", "value":11},
          {'name':"开发技术", "value":43},
          {'name':"具有扎实", "value":13},
          {'name':"开源项目", "value":13},
          {'name':"相关产品", "value":15},
          {'name':"掌握主流", "value":13},
          {'name':"编程习惯", "value":13},
          {'name':"协调能力", "value":24},
          {'name':"前端技术", "value":17},
          {'name':"平台架构", "value":17},
          {'name':"性能调", "value":34},
          {'name':"理解业务", "value":14},
          {'name':"公司产品", "value":21},
          {'name':"强烈责任心", "value":11},
          {'name':"提高系统", "value":13},
          {'name':"保证系统", "value":15},
          {'name':"系统高", "value":12},
          {'name':"合作意识", "value":15},
          {'name':"难题攻关", "value":11},
          {'name':"负责公司", "value":36},
          {'name':"常用数据库", "value":12},
          {'name':"全日制本科", "value":23},
          {'name':"相关开发", "value":19},
          {'name':"优化经验", "value":16},
          {'name':"开发模式", "value":13},
          {'name':"架构设计", "value":126},
          {'name':"具有良好", "value":54},
          {'name':"喜欢钻研", "value":18},
          {'name':"开发计划", "value":12},
          {'name':"网络编程", "value":19},
          {'name':"较强学习", "value":23},
          {'name':"精通线", "value":14},
          {'name':"独立完成", "value":33},
          {'name':"模块开发", "value":17},
          {'name':"平台开发", "value":15},
          {'name':"开发规范", "value":16},
          {'name':"理解面向", "value":12},
          {'name':"熟悉设计", "value":19},
          {'name':"核心功能", "value":22},
          {'name':"功能模块", "value":24},
          {'name':"关系型", "value":25},
          {'name':"具备较强", "value":17},
          {'name':"常用开源", "value":15},
          {'name':"良好学习", "value":17},
          {'name':"扎实计算机", "value":15},
          {'name':"相关专业", "value":174},
          {'name':"逻辑思维能力", "value":24},
          {'name':"熟悉掌握", "value":13},
          {'name':"熟悉前端", "value":15},
          {'name':"设计优化", "value":15},
          {'name':"编码习惯", "value":13},
          {'name':"精通数据库", "value":11},
          {'name':"良好编码", "value":20},
          {'name':"设计应用", "value":19},
          {'name':"架构优化", "value":13},
          {'name':"熟悉常用", "value":57},
          {'name':"调优", "value":83},
          {'name':"良好编程", "value":11},
          {'name':"分析设计", "value":31},
          {'name':"功能设计", "value":16},
          {'name':"掌握线", "value":12},
          {'name':"文档编写", "value":37},
          {'name':"数据结构", "value":54},
          {'name':"强烈兴趣", "value":12},
          {'name':"熟悉主流", "value":44},
          {'name':"开发语言", "value":15},
          {'name':"团队成员", "value":14},
          {'name':"设计能力", "value":48},
          {'name':"对象设计", "value":30},
          {'name':"基础知识", "value":25},
          {'name':"能够独立", "value":16},
          {'name':"方案讨论", "value":12},
          {'name':"设计经验", "value":40},
          {'name':"端开发", "value":30},
          {'name':"工作经验", "value":83},
          {'name':"快速定位", "value":13},
          {'name':"后台开发", "value":12},
          {'name':"沟通表达", "value":17},
          {'name':"计算机基础", "value":12},
          {'name':"服务端", "value":23},
          {'name':"技术攻关", "value":13},
          {'name':"代码开发", "value":25},
          {'name':"负责产品", "value":12},
          {'name':"熟悉开发", "value":25},
          {'name':"编程基础", "value":25},
          {'name':"实现原理", "value":11},
          {'name':"具备良好", "value":68},
          {'name':"职位描述", "value":26},
          {'name':"常用技术", "value":13},
          {'name':"实践经验", "value":20},
          {'name':"性能优化", "value":60},
          {'name':"编写能力", "value":15},
          {'name':"进行开发", "value":17},
          {'name':"并发高", "value":35},
          {'name':"沟通团队", "value":13},
          {'name':"掌握数据库", "value":12},
          {'name':"完成项目", "value":22},
          {'name':"相关知识", "value":11},
          {'name':"消息中间", "value":31},
          {'name':"学习能力", "value":74},
          {'name':"线集合", "value":25},
          {'name':"设计代码", "value":11},
          {'name':"代码质量", "value":16},
          {'name':"理解能力", "value":14},
          {'name':"熟悉缓存", "value":43},
          {'name':"单元测试", "value":31},
          {'name':"良好沟通", "value":93},
          {'name':"系统核心", "value":11},
          {'name':"解决系统", "value":14},
          {'name':"服务框架", "value":23},
          {'name':"高性能", "value":23},
          {'name':"负责项目", "value":16},
          {'name':"负载均衡", "value":11},
          {'name':"主流数据库", "value":20},
          {'name':"能够熟练", "value":14},
          {'name':"系统架构", "value":70},
          {'name':"合作精神", "value":44},
          {'name':"系统进行", "value":12},
          {'name':"开发设计", "value":20},
          {'name':"完成开发", "value":14},
          {'name':"熟悉数据", "value":12},
          {'name':"分析解决问题", "value":25},
          {'name':"熟悉面向", "value":20},
          {'name':"确保项目", "value":12},
          {'name':"深刻理解", "value":22},
          {'name':"缓存消息", "value":49},
          {'name':"服务架构", "value":52},
          {'name':"代码编写", "value":41},
          {'name':"良好面向", "value":12},
          {'name':"使用语言", "value":11},
          {'name':"基础框架", "value":26},
          {'name':"思路清晰", "value":20},
          {'name':"集合基础", "value":28},
          {'name':"问题能力", "value":12},
          {'name':"优先考虑", "value":44},
          {'name':"负责核心", "value":15},
          {'name':"复杂业务", "value":19},
          {'name':"开源框架", "value":77},
          {'name':"热爱技术", "value":14},
          {'name':"开发测试", "value":13},
          {'name':"良好团队", "value":54},
          {'name':"计算机软件相关", "value":13},
          {'name':"结构设计", "value":12},
          {'name':"基础技术", "value":12},
          {'name':"业务需求", "value":50},
          {'name':"型数据库", "value":23},
          {'name':"难点攻关", "value":12},
          {'name':"团队合作", "value":83},
          {'name':"中的技术", "value":18},
          {'name':"软件开发", "value":58},
          {'name':"概要设计", "value":16},
          {'name':"常用命令", "value":19},
          {'name':"参与系统", "value":21},
          {'name':"设计工作", "value":18},
          {'name':"核心模块", "value":24},
          {'name':"使用开发", "value":13},
          {'name':"开发维护", "value":29},
          {'name':"技术问题", "value":41},
          {'name':"关键技术", "value":12},
          {'name':"能力团队", "value":36},
          {'name':"线并发", "value":15},
          {'name':"设计文档", "value":23},
          {'name':"合作能力", "value":19},
          {'name':"技术难题", "value":32},
          {'name':"能力强", "value":41},
          {'name':"工作内容", "value":12},
          {'name':"具有较强", "value":16},
          {'name':"项目经验", "value":31},
          {'name':"熟悉微", "value":20},
          {'name':"专业本科", "value":43},
          {'name':"熟悉使用", "value":18},
          {'name':"功能开发", "value":19},
          {'name':"前端开发", "value":16},
          {'name':"解决项目", "value":11},
          {'name':"模块设计", "value":36},
          {'name':"具有一定", "value":12},
          {'name':"主流开发", "value":25},
          {'name':"产品需求", "value":30},
          {'name':"结构算法", "value":30},
          {'name':"负责系统", "value":22},
          {'name':"任职要求", "value":169},
          {'name':"面向对象", "value":64},
          {'name':"岗位要求", "value":50},
          {'name':"框架开发", "value":11},
          {'name':"产品功能", "value":12},
          {'name':"系统需求分析", "value":12},
          {'name':"系统分析设计", "value":13},
          {'name':"进行系统", "value":12},
          {'name':"技术栈", "value":19},
          {'name':"协作能力", "value":27},
          {'name':"线编程", "value":22},
          {'name':"深入了解", "value":14},
          {'name':"相关技术", "value":66},
          {'name':"业务理解", "value":11},
          {'name':"互联网行业", "value":13},
          {'name':"数据库设计", "value":44},
          {'name':"设计开发", "value":92},
          {'name':"方案设计", "value":17},
          {'name':"认真负责", "value":13},
          {'name':"技术方案", "value":25},
          {'name':"基础扎实", "value":71},
          {'name':"维护升级", "value":11},
          {'name':"工作职责", "value":59},
          {'name':"开发相关", "value":20},
          {'name':"扎实编程", "value":17},
          {'name':"解决开发", "value":18},
          {'name':"熟悉应用", "value":17},
          {'name':"熟练掌握", "value":103},
          {'name':"熟悉线", "value":29},
          {'name':"熟悉网络", "value":12},
          {'name':"团队管理", "value":12},
          {'name':"开发流程", "value":17},
          {'name':"常用设计", "value":36},
          {'name':"敏捷开发", "value":14},
          {'name':"实际项目", "value":14},
          {'name':"技术文档", "value":50},
          {'name':"设计编码", "value":19},
          {'name':"业务系统", "value":23},
          {'name':"设计研发", "value":20},
          {'name':"开发工具", "value":16},
          {'name':"技术难点", "value":20},
          {'name':"应用系统", "value":12},
          {'name':"解决问题能力", "value":36},
          {'name':"善于思考", "value":11},
          {'name':"具备扎实", "value":13},
          {'name':"核心代码", "value":38},
          {'name':"抗压能力", "value":31},
          {'name':"开发工作", "value":77},
          {'name':"职责描述", "value":77},
          {'name':"持续优化", "value":16},
          {'name':"计算机相关", "value":131},
          {'name':"系统性能", "value":13},
          {'name':"团队协作", "value":51},
          {'name':"熟悉常见", "value":26},
          {'name':"开发框架", "value":59},
          {'name':"数据库使用", "value":15},
          {'name':"技术框架", "value":33},
          {'name':"相关工作", "value":22},
          {'name':"逻辑分析", "value":11},
          {'name':"缓存技术", "value":18},
          {'name':"应用经验", "value":15},
          {'name':"具有很强", "value":12},
          {'name':"应用场景", "value":12},
          {'name':"研发工作", "value":26},
          {'name':"产品研发", "value":16},
          {'name':"主流框架", "value":17},
          {'name':"选型", "value":18},
          {'name':"分析解决", "value":11},
          {'name':"参与项目", "value":15},
          {'name':"技术规划", "value":11},
          {'name':"系统设计开发", "value":21},
          {'name':"熟练应用", "value":14},
          {'name':"相关文档", "value":11},
          {'name':"过程中", "value":12},
          {'name':"熟悉数据库", "value":56},
          {'name':"工作认真", "value":12},
          {'name':"技术选", "value":12},
          {'name':"相关系统", "value":13},
          {'name':"消息搜索", "value":12},
          {'name':"技术体系", "value":15},
          {'name':"项目相关", "value":12},
          {'name':"使用数据库", "value":17},
          {'name':"应用服务器", "value":26},
          {'name':"本科学历", "value":184},
          {'name':"熟悉技术", "value":19},
          {'name':"积极主动", "value":21},
          {'name':"常用开发", "value":11},
          {'name':"进行技术", "value":17},
          {'name':"过程中的", "value":17},
          {'name':"经验优先", "value":166},
          {'name':"沟通协调", "value":18},
          {'name':"产品架构", "value":11},
          {'name':"服务治理", "value":12},
          {'name':"工作压力", "value":18},
          {'name':"优经验", "value":17},
          {'name':"参与业务", "value":12},
          {'name':"常用数据", "value":13},
          {'name':"项目进度", "value":23},
          {'name':"高可用", "value":31},
          {'name':"实战经验", "value":14},
          {'name':"掌握语言", "value":14},
          {'name':"应用开发", "value":27},
          {'name':"设计实现", "value":23},
          {'name':"基本原理", "value":11},
          {'name':"使用经验", "value":19},
          {'name':"高负载", "value":11},
          {'name':"独立分析", "value":21},
          {'name':"开发过程", "value":30},
          {'name':"开发任务", "value":30},
          {'name':"核心技术", "value":14},
          {'name':"开发人员", "value":17},
          {'name':"系统设计", "value":40},
          {'name':"扎实基础", "value":15},
          {'name':"主流开源", "value":31},
          {'name':"责任心强", "value":18},
          {'name':"技术强烈", "value":11},
          {'name':"技术架构", "value":27},
          {'name':"精通语言", "value":24},
          {'name':"项目开发", "value":56},
          {'name':"开发经验", "value":231},
          {'name':"消息队列", "value":24},
          {'name':"微服务", "value":100},
          {'name':"大学本科", "value":13},
          {'name':"技术预研", "value":12},
          {'name':"分析能力", "value":15},
          {'name':"产品开发", "value":26},
          {'name':"参与产品", "value":19},
          {'name':"开发项目", "value":17},
          {'name':"一定了解", "value":21},]
      }
    },
    methods: {
      showWords () {
        let myChart = this.$echarts.init(document.getElementById('main'))
        let datas = this.datas

        let option = {
          tooltip: {
            show: true,
            position: 'top',
            textStyle: {
              fontSize: 30
            }
          },
          backgroundColor:'#4B0082',
          series: [{
            type: "wordCloud",
            // 网格大小，各项之间间距
            gridSize: 12,
            // 形状 circle 圆，cardioid  心， diamond 菱形，
            // triangle-forward 、triangle 三角，star五角星
            shape: 'circle',
            // 字体大小范围
            sizeRange: [20, 50],
            // 文字旋转角度范围
            rotationRange: [-90, 90],
            // 旋转步值
            // rotationStep: 50,
            // 自定义图形
            // maskImage: maskImage,
            left: 'center',
            top: 'center',
            right: null,
            bottom: null,
            // 画布宽
            width: '90%',
            // 画布高
            height: '80%',
            // 是否渲染超出画布的文字
            drawOutOfBound: false,
            textStyle: {
              normal: {
                color: function() {
                  return 'rgb(' + [
                    Math.round(Math.random() * 200 + 55),
                    Math.round(Math.random() * 200 + 55),
                    Math.round(Math.random() * 200 + 55)
                  ].join(',') + ')';
                }
              },
              emphasis: {
                shadowBlur: 10,
                shadowColor: '#2ac'
              }
            },
            data: datas
          }]
        };
        myChart.setOption(option)
      }
    },
    mounted () {
      this.showWords()
    }
  }
</script>

