
<template>
    <div id="app" style="text-align: center;width: 90%; margin: auto;margin-top: 2%">
        <div id="main" style="width: 100%;height:600px;margin:0 auto"></div>
    </div>
</template>
<script>
  require('echarts-wordcloud')
  export default {
    name: 'webWordCloud',
    data () {
      return {
        datas:[{'name':"良好团队", "value":39},
          {'name':"配合后台", "value":16},
          {'name':"沟通协作", "value":11},
          {'name':"模块化开发", "value":17},
          {'name':"相关项目", "value":11},
          {'name':"框架设计", "value":20},
          {'name':"业务需求", "value":14},
          {'name':"团队合作", "value":51},
          {'name':"专业毕业", "value":13},
          {'name':"熟悉移动", "value":11},
          {'name':"软件开发", "value":13},
          {'name':"表达能力", "value":20},
          {'name':"参与公司", "value":13},
          {'name':"化深刻", "value":13},
          {'name':"端页面", "value":13},
          {'name':"项目前端", "value":24},
          {'name':"统招本科", "value":21},
          {'name':"问题解决问题", "value":12},
          {'name':"开发维护", "value":39},
          {'name':"分析问题", "value":11},
          {'name':"相关经验", "value":16},
          {'name':"表现数据", "value":12},
          {'name':"任职资格", "value":56},
          {'name':"沟通能力", "value":55},
          {'name':"善于沟通", "value":12},
          {'name':"能力团队", "value":32},
          {'name':"熟悉协议", "value":18},
          {'name':"熟练使用", "value":113},
          {'name':"深入理解", "value":30},
          {'name':"语义化", "value":24},
          {'name':"负责移动", "value":11},
          {'name':"熟悉页面", "value":16},
          {'name':"实现产品", "value":19},
          {'name':"经理设计师", "value":16},
          {'name':"大专学历", "value":12},
          {'name':"前端界面", "value":11},
          {'name':"精通开发", "value":11},
          {'name':"主流浏览器", "value":29},
          {'name':"前端自动化", "value":11},
          {'name':"端移动", "value":15},
          {'name':"页面架构", "value":20},
          {'name':"研究新技术", "value":18},
          {'name':"协作精神", "value":18},
          {'name':"能力强", "value":32},
          {'name':"设计方案", "value":11},
          {'name':"解决浏览器", "value":17},
          {'name':"开发技术", "value":52},
          {'name':"熟悉框架", "value":13},
          {'name':"项目经验", "value":47},
          {'name':"完成数据", "value":11},
          {'name':"新技术调研", "value":17},
          {'name':"专业本科", "value":25},
          {'name':"编程习惯", "value":11},
          {'name':"功能开发", "value":26},
          {'name':"前端技术", "value":104},
          {'name':"前端开发", "value":207},
          {'name':"良好代码", "value":17},
          {'name':"产品需求", "value":30},
          {'name':"访问性", "value":17},
          {'name':"公司产品", "value":21},
          {'name':"面向对象", "value":28},
          {'name':"前端工程化", "value":32},
          {'name':"框架开发", "value":11},
          {'name':"数据分离", "value":12},
          {'name':"产品功能", "value":11},
          {'name':"岗位职责", "value":124},
          {'name':"界面开发", "value":14},
          {'name':"数据接口", "value":15},
          {'name':"端数据", "value":15},
          {'name':"用户交互", "value":15},
          {'name':"前端性能", "value":29},
          {'name':"技术栈", "value":20},
          {'name':"负责公司", "value":51},
          {'name':"协作能力", "value":27},
          {'name':"程序开发", "value":30},
          {'name':"响应式", "value":14},
          {'name':"开发工程师", "value":12},
          {'name':"调试工具", "value":17},
          {'name':"深入了解", "value":12},
          {'name':"相关技术", "value":33},
          {'name':"全日制本科", "value":20},
          {'name':"相关开发", "value":15},
          {'name':"前端基础", "value":16},
          {'name':"设计开发", "value":61},
          {'name':"实际开发", "value":12},
          {'name':"至少熟悉", "value":19},
          {'name':"优化经验", "value":18},
          {'name':"前端工作", "value":16},
          {'name':"技术方案", "value":12},
          {'name':"熟悉端", "value":24},
          {'name':"基础扎实", "value":11},
          {'name':"工作职责", "value":42},
          {'name':"端工程师", "value":26},
          {'name':"开发模式", "value":20},
          {'name':"架构设计", "value":35},
          {'name':"开发相关", "value":16},
          {'name':"具有良好", "value":35},
          {'name':"产品用户", "value":12},
          {'name':"熟练掌握", "value":99},
          {'name':"较强学习", "value":18},
          {'name':"优化前端", "value":32},
          {'name':"开发流程", "value":18},
          {'name':"前端组件", "value":24},
          {'name':"应用程序", "value":11},
          {'name':"实际项目", "value":28},
          {'name':"网站前端", "value":17},
          {'name':"管理工具", "value":12},
          {'name':"技术文档", "value":13},
          {'name':"独立完成", "value":25},
          {'name':"熟悉标准", "value":25},
          {'name':"前端体验", "value":11},
          {'name':"交互效果", "value":17},
          {'name':"开发规范", "value":19},
          {'name':"解决问题能力", "value":31},
          {'name':"良好学习", "value":15},
          {'name':"良好兼容性", "value":12},
          {'name':"抗压能力", "value":14},
          {'name':"相关专业", "value":124},
          {'name':"开发工作", "value":83},
          {'name':"职责描述", "value":63},
          {'name':"持续优化", "value":26},
          {'name':"计算机相关", "value":96},
          {'name':"团队协作", "value":46},
          {'name':"熟悉前端", "value":50},
          {'name':"完成页面", "value":11},
          {'name':"熟悉常见", "value":13},
          {'name':"开发框架", "value":44},
          {'name':"组件化", "value":14},
          {'name':"浏览器兼容", "value":25},
          {'name':"一定理解", "value":11},
          {'name':"良好编码", "value":13},
          {'name':"构建工具", "value":37},
          {'name':"五险金", "value":17},
          {'name':"熟悉常用", "value":20},
          {'name':"打包工具", "value":13},
          {'name':"调优", "value":15},
          {'name':"相关工作", "value":37},
          {'name':"页面性能", "value":27},
          {'name':"逻辑分析", "value":12},
          {'name':"浏览器兼容性", "value":46},
          {'name':"前端设计", "value":26},
          {'name':"文档编写", "value":14},
          {'name':"研发工作", "value":12},
          {'name':"前端架构", "value":34},
          {'name':"技术研究", "value":27},
          {'name':"前端代码", "value":25},
          {'name':"主流框架", "value":19},
          {'name':"选型", "value":15},
          {'name':"开发调试", "value":14},
          {'name':"用户体验", "value":84},
          {'name':"用户需求", "value":12},
          {'name':"参与项目", "value":12},
          {'name':"完成产品", "value":12},
          {'name':"前端功能", "value":16},
          {'name':"熟悉主流", "value":22},
          {'name':"开发语言", "value":11},
          {'name':"交互设计", "value":23},
          {'name':"设计能力", "value":20},
          {'name':"组件库", "value":20},
          {'name':"端交互", "value":12},
          {'name':"具备优秀", "value":11},
          {'name':"了解前端", "value":17},
          {'name':"基础知识", "value":15},
          {'name':"前端页面", "value":49},
          {'name':"技术选", "value":11},
          {'name':"端开发", "value":58},
          {'name':"工作经验", "value":101},
          {'name':"完成前端", "value":21},
          {'name':"后台开发", "value":35},
          {'name':"沟通表达", "value":14},
          {'name':"产品前端", "value":45},
          {'name':"持续改进", "value":13},
          {'name':"乐于分享", "value":11},
          {'name':"团队意识", "value":12},
          {'name':"服务端", "value":18},
          {'name':"参与前端", "value":15},
          {'name':"前端框架", "value":85},
          {'name':"项目需求", "value":14},
          {'name':"产品项目", "value":12},
          {'name':"提升用户", "value":15},
          {'name':"数据交互", "value":19},
          {'name':"本科学历", "value":149},
          {'name':"负责产品", "value":20},
          {'name':"易用性改进", "value":12},
          {'name':"交互功能", "value":17},
          {'name':"熟悉开发", "value":20},
          {'name':"兼容问题", "value":14},
          {'name':"产品设计", "value":30},
          {'name':"具备良好", "value":44},
          {'name':"职位描述", "value":21},
          {'name':"实践经验", "value":26},
          {'name':"积极主动", "value":12},
          {'name':"性能优化", "value":81},
          {'name':"熟练运用", "value":23},
          {'name':"进行开发", "value":12},
          {'name':"前沿技术", "value":28},
          {'name':"入职", "value":14},
          {'name':"开发实现", "value":13},
          {'name':"经验优先", "value":132},
          {'name':"热爱前端", "value":11},
          {'name':"技术实现", "value":11},
          {'name':"工作压力", "value":22},
          {'name':"至少前端", "value":16},
          {'name':"完成项目", "value":14},
          {'name':"配合产品", "value":21},
          {'name':"学习能力", "value":62},
          {'name':"前端研发", "value":12},
          {'name':"对象编程", "value":14},
          {'name':"代码质量", "value":14},
          {'name':"维护性", "value":15},
          {'name':"端分离", "value":20},
          {'name':"负责网站", "value":12},
          {'name':"前端产品", "value":12},
          {'name':"应用开发", "value":21},
          {'name':"良好沟通", "value":53},
          {'name':"兼容性问题", "value":24},
          {'name':"移动端", "value":66},
          {'name':"技术优化", "value":12},
          {'name':"维护优化", "value":17},
          {'name':"跨浏览器", "value":15},
          {'name':"善于学习", "value":12},
          {'name':"设计实现", "value":16},
          {'name':"系统前端", "value":23},
          {'name':"独立开发", "value":14},
          {'name':"高性能", "value":15},
          {'name':"公司前端", "value":13},
          {'name':"使用经验", "value":14},
          {'name':"后台工程师", "value":11},
          {'name':"负责项目", "value":11},
          {'name':"能力沟通", "value":14},
          {'name':"能够熟练", "value":15},
          {'name':"掌握前端", "value":34},
          {'name':"使用前端", "value":26},
          {'name':"合作精神", "value":28},
          {'name':"开发人员", "value":39},
          {'name':"负责前端", "value":71},
          {'name':"工程师协作", "value":13},
          {'name':"前端项目", "value":14},
          {'name':"责任心强", "value":19},
          {'name':"主流前端", "value":20},
          {'name':"分析解决问题", "value":13},
          {'name':"编程思想", "value":18},
          {'name':"页面开发", "value":22},
          {'name':"职位要求", "value":18},
          {'name':"版本管理", "value":11},
          {'name':"产品界面", "value":14},
          {'name':"前端应用", "value":12},
          {'name':"深刻理解", "value":43},
          {'name':"项目开发", "value":53},
          {'name':"开发经验", "value":207},
          {'name':"产品经理", "value":38},
          {'name':"进行前端", "value":11},
          {'name':"代码编写", "value":30},
          {'name':"前端构建", "value":11},
          {'name':"端语言", "value":12},
          {'name':"微信程序", "value":21},
          {'name':"分离语义", "value":12},
          {'name':"架构布局", "value":20},
          {'name':"开发能力", "value":13},
          {'name':"优先考虑", "value":33},
          {'name':"理解标准", "value":19},
          {'name':"分析能力", "value":16},
          {'name':"产品开发", "value":25},
          {'name':"精通前端", "value":47},
          {'name':"参与产品", "value":24},
          {'name':"开发项目", "value":14},
          {'name':"一定了解", "value":16},
        ]
      }
    },
    methods: {
      showWords () {
        let myChart = this.$echarts.init(document.getElementById('main'))
        let datas = this.datas



        let option = {
          tooltip: {
            show: true,
            position: 'top',
            textStyle: {
              fontSize: 30
            }
          },
          backgroundColor:'#008B8B',
          series: [{
            type: "wordCloud",
            // 网格大小，各项之间间距
            gridSize: 12,
            // 形状 circle 圆，cardioid  心， diamond 菱形，
            // triangle-forward 、triangle 三角，star五角星
            shape: 'circle',
            // 字体大小范围
            sizeRange: [20, 50],
            // 文字旋转角度范围
            rotationRange: [-90, 90],
            // 旋转步值
            // rotationStep: 50,
            // 自定义图形
            // maskImage: maskImage,
            left: 'center',
            top: 'center',
            right: null,
            bottom: null,
            // 画布宽
            width: '90%',
            // 画布高
            height: '80%',
            // 是否渲染超出画布的文字
            drawOutOfBound: false,
            textStyle: {
              normal: {
                color: function() {
                  return 'rgb(' + [
                    Math.round(Math.random() * 200 + 55),
                    Math.round(Math.random() * 200 + 55),
                    Math.round(Math.random() * 200 + 55)
                  ].join(',') + ')';
                }
              },
              emphasis: {
                shadowBlur: 10,
                shadowColor: '#2ac'
              }
            },
            data: datas
          }]
        };
        myChart.setOption(option)
      }
    },
    mounted () {
      this.showWords()
    }
  }
</script>

